### PR TITLE
Fix to #271

### PR DESCRIPTION
**Pull request by yongs2**
Update Radix to 3.8.1 to work with redis 7. [mediocregopher/radix#322](https://github.com/mediocregopher/radix/pull/322)

I have completed test with redis cluster 7.0.7.

### CODE REVIEW

**Comment by gregorg** [comment]
any update on this ? #271  is waiting on it

**Comment by GoodGoodJM** [comment]
@mikhail-vl Why this mr does not meged?

**Review by GoodGoodJM — APPROVED** [review]

**Comment by gregorg** [comment]
@mikhail-vl  this project looks to be dead. Please remove merging restrictions, and add active reviewers. Thanks!

**Comment by mikhail-vl** [comment]
@gregorg Please contact the Redis team @K-Jo.

**Comment by gregorg** [comment]
@mikhail-vl  Can't you just approve and merge this PR until @K-Jo looks for a more durable solution ?

**Review by slorello89 — CHANGES_REQUESTED** [review]
Hi @yongs2 - Thanks for submitting this - sorry for the delayed response - I just took over maintenance of our Grafana stuff so hello there :). 

There's an awful lot of mod changes/additions here than necessary to upgrade to radix-v3.8.1 - can you please reduce the changes here so it's the minimum to accomplish what we are looking for here (upgrading to 3.8.1 to fix the new cluster bits)

Thanks!

**Comment by yongs2** [comment]
Hi @slorello89,

Referring to [Developing Redis Data Source](https://redisgrafana.github.io/development/redis-datasource/), I would follow the steps "Install Grafana plugin SDK for Go dependency" and "Install Mage (make-like build tool using Go)".

To build, I need to call "go get -u -d ./...", which will change the contents of go.mod to the latest information.

Thanks

**Review by slorello89 — APPROVED** [review]
@yongs2 - yeah looks like those superfluous upgrades broke the CI - pushed an update to just upgrade radix version - hopefully that's alright - wanted to make sure you maintained credit. this LGTM 👍  now. Next challenge is working out how to release this :)

Thanks for this!

**Pull request merged**
