### PR TITLE
Fix "NOAUTH Authentication required" error with sentinel

### LINKED ISSUE #92: Get "NOAUTH Authentication required" error with sentinel
I have redis/sentinel cluster. Redis and sentinel have 'requirepass' param in config (password equal).

When I configure datasource for sentinel I get error "NOAUTH Authentication required", but if I set standalone plugin works.

### PR DESCRIPTION
**Pull request by mikhailredis**
Resolves #92

### CODE REVIEW

**Review by mikhailredis — COMMENTED** [review]
Looks good!

**Comment by monkeymq** [comment]
I think this problem still exists in version 1.3.1, redis version I use is 6.0.4, sentinel mode

**Comment by mikhailredis** [comment]
@monkeymq, could you please provide steps to reproduce the issue.

**Comment by monkeymq** [comment]
> @monkeymq, could you please provide steps to reproduce the issue.

@mikhailredis hello, this is my configuration, could you help me out?
image

**Pull request merged**
